//navigator.clipboard.writeText("Ciaone")


let loremData = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sollicitudin ante justo, gravida faucibus dui luctus vulputate. Sed fermentum placerat odio. Nulla sit amet quam bibendum, placerat odio quis, fermentum ante. Maecenas dictum convallis sagittis. Nulla in enim a leo elementum varius vel ac diam. Vestibulum at felis turpis. Duis congue pretium felis, vitae convallis metus imperdiet accumsan. Proin sollicitudin placerat ipsum.",
    "Aenean vestibulum turpis et elementum commodo. Donec porttitor accumsan libero, id dictum leo euismod facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse nulla diam, interdum non magna quis, tempor feugiat ante. Morbi convallis, dui vel placerat porttitor, orci elit blandit tellus, eget congue nulla nunc pharetra arcu. Morbi et dapibus libero. Nulla dictum nec justo vitae cursus. Duis faucibus orci ut sapien gravida tempor. Vivamus luctus auctor ligula nec maximus. Fusce placerat justo ut elit accumsan mattis non ac magna.",
    "Donec congue pulvinar urna, vitae convallis dolor volutpat in. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin tristique, purus non suscipit placerat, tortor nisl semper tellus, sit amet hendrerit leo felis vel velit. Aenean sit amet mauris eu lacus rhoncus dapibus ac commodo felis. Maecenas sed finibus mi. Duis vestibulum scelerisque ligula a tempor. Donec condimentum ligula a risus molestie sodales.",
    "Sed sed ullamcorper ante, quis porttitor odio. Morbi eget erat enim. Sed dui eros, maximus eget diam in, porta gravida ante. Pellentesque nisl libero, ornare non blandit sit amet, sollicitudin non risus. Aliquam malesuada massa nisl, non convallis dui iaculis in. Phasellus vestibulum metus ac lacus laoreet consequat. In hac habitasse platea dictumst. Vestibulum tincidunt neque eget velit dignissim ultrices. Sed ut eros sollicitudin, mattis nibh vitae, sodales dolor. Etiam pulvinar erat eu erat posuere, sed tempus mauris fringilla. Donec rutrum odio maximus arcu efficitur ultricies. Vivamus hendrerit, mi sit amet sollicitudin pretium, tortor magna pharetra tortor, id blandit nibh leo sed nunc.",
    "Curabitur rhoncus, sem sed venenatis sagittis, turpis sem tristique ante, et tincidunt nisl magna in ex. Nam egestas commodo sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus lacinia vehicula risus ac rutrum. Donec blandit ultricies sapien sed iaculis. Etiam luctus, ipsum lacinia elementum hendrerit, ante sapien varius diam, eget sagittis sem nibh quis elit. Donec purus ex, facilisis sit amet magna non, lacinia rhoncus nulla. Phasellus aliquam nulla justo, eu ornare felis laoreet a. Cras sed mi ultrices ante accumsan semper ut a enim. Fusce volutpat quam non ipsum ornare, sed efficitur erat posuere. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Interdum et malesuada fames ac ante ipsum primis in faucibus. In sit amet nibh tempus, pretium elit ut, tincidunt lorem.",
    "Sed sollicitudin, eros vel lacinia elementum, ex velit euismod est, sit amet aliquam massa enim in felis. Cras quis erat sit amet mi accumsan egestas. Donec quis massa in leo placerat tempus ac ac elit. In in lacus ac sapien lobortis hendrerit ac at lorem. Pellentesque ut orci quis ante euismod ullamcorper. Donec posuere risus purus, et congue turpis porttitor ut. Quisque sed tempor quam. In condimentum turpis id augue semper rutrum. Nam efficitur risus ac mattis condimentum. Sed fermentum cursus venenatis. Proin aliquam ipsum non lacinia mattis. Fusce blandit odio nec diam blandit laoreet. Cras pretium felis et arcu mollis, eget semper ipsum volutpat. Sed efficitur non sem ut semper. Ut sed lacinia lectus.",
    "Quisque a magna ac mi auctor molestie laoreet sit amet nibh. Nulla pharetra, neque vel laoreet blandit, diam ante fringilla augue, quis tincidunt justo lorem nec tellus. Aliquam pellentesque bibendum leo quis feugiat. Fusce lacinia purus nisl, eu convallis nulla rhoncus id. Nullam suscipit efficitur pharetra. Aenean erat justo, pharetra eget dictum nec, ultrices et erat. Morbi tempor felis ut dignissim volutpat. Quisque varius neque quis ligula consectetur ornare id ac diam. Quisque gravida eros nulla, consequat luctus quam volutpat eu. Mauris vitae fermentum ante. Duis felis ex, rutrum aliquet blandit porttitor, pellentesque pellentesque lorem. Aliquam erat volutpat. Morbi eget magna vitae lorem ultricies fermentum. Sed blandit erat eget dolor iaculis, sed auctor leo sodales. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tincidunt neque nec ex porttitor sodales.    ",
    "Curabitur tempor euismod libero, pellentesque mollis augue luctus quis. Donec venenatis accumsan lorem, ac cursus nulla accumsan eget. Nam porta nisi ex. Maecenas tincidunt velit at nunc dapibus, ac interdum eros pharetra. Quisque id magna nulla. Vestibulum nec leo ullamcorper, molestie orci id, iaculis velit. Phasellus massa purus, commodo vitae lobortis ut, posuere quis neque. Donec ac neque gravida, finibus neque at, tincidunt neque. Pellentesque semper urna sit amet imperdiet egestas. Nunc et imperdiet risus. In commodo ante libero, et hendrerit justo gravida a. Etiam venenatis tempor ligula, eget fermentum elit varius ut. In eu sem rutrum, efficitur nibh in, ultrices velit. Aenean nec nunc hendrerit tellus consequat commodo vitae at eros. Fusce tincidunt auctor enim vitae porta. Nullam fermentum velit id ligula scelerisque pharetra.",
    "Etiam iaculis, nisl et feugiat posuere, tellus turpis mollis quam, nec commodo quam ex sit amet nulla. Maecenas eros eros, vestibulum quis erat vel, rhoncus accumsan quam. Mauris vel dolor a ipsum scelerisque eleifend sit amet et nibh. Aliquam erat volutpat. Nunc dapibus lorem sed dui viverra molestie. Curabitur tincidunt elit nulla. Nulla dolor leo, cursus id vehicula ut, eleifend in ante.",
    "Praesent suscipit imperdiet lorem. Nulla vitae eleifend urna. Pellentesque ac bibendum odio. Cras pellentesque risus sit amet mauris faucibus pharetra. Donec commodo semper placerat. Curabitur justo risus, euismod id erat non, laoreet placerat urna. Sed laoreet tellus eget turpis sodales, ac mollis nisl iaculis. Maecenas feugiat porta ligula, vel vulputate neque feugiat eget.",
    "Nulla sit amet tortor a ex blandit dictum. Etiam pulvinar, nulla vitae hendrerit ornare, ligula nulla tincidunt metus, eget malesuada orci turpis nec turpis. Phasellus aliquam lacinia ex, nec bibendum turpis ultrices quis. Nullam et blandit purus, eu eleifend dolor. Nulla facilisi. Suspendisse mattis aliquet purus fringilla dignissim. Duis congue enim sed feugiat hendrerit. Pellentesque mollis ipsum vehicula neque maximus molestie. Sed quis enim sit amet nulla consequat viverra. Ut ut orci lorem.",
    "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis finibus id nunc eget elementum. Mauris ultrices quis sapien quis facilisis. Sed iaculis, ex ut ullamcorper aliquet, sapien libero volutpat sapien, a vulputate sapien libero at dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut non nisi ac libero placerat commodo eget nec nisi. Praesent congue tempor nisl. Pellentesque lacinia massa eget vulputate sollicitudin. Sed ut neque et ex dapibus egestas. Proin egestas mi quis justo egestas, et tempor ante porttitor.",
    "Sed sed tempor leo. Aenean nec tincidunt ex. Sed maximus auctor tempor. Quisque non varius est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vel nulla nec velit egestas fringilla. Suspendisse potenti. Sed condimentum ligula id ipsum imperdiet mattis. Quisque faucibus lectus purus, vel euismod ligula tincidunt id. Nullam odio nulla, viverra quis finibus eget, fermentum ut felis.",
    "Pellentesque elementum diam et urna tincidunt, sit amet placerat diam bibendum. Suspendisse lacus ipsum, tincidunt eu erat id, commodo aliquam arcu. Duis dictum risus arcu, eget hendrerit augue dictum vitae. Cras pharetra mi a felis molestie, quis imperdiet ante laoreet. Nunc at nisl molestie, pulvinar augue quis, auctor sapien. Aenean eget commodo est. Curabitur volutpat convallis mauris, eget suscipit odio congue at. Etiam consequat velit ac posuere gravida. Maecenas vel purus at neque consequat rutrum. Donec turpis odio, venenatis varius ligula sit amet, volutpat interdum tortor. Mauris in ex quis dui pellentesque varius quis eu odio. Aenean ut mi ut erat lobortis aliquet. Praesent id turpis venenatis, scelerisque elit quis, congue est. Aenean ante enim, porttitor ut ligula eu, sagittis blandit purus. Sed venenatis tristique pretium. Proin volutpat commodo rhoncus.",
    "Donec velit dolor, vestibulum ut arcu ut, tincidunt condimentum orci. Mauris viverra a ligula id finibus. Pellentesque bibendum interdum dui, ac ullamcorper ipsum facilisis dictum. Proin fringilla odio ut dui tristique, vitae commodo tellus vehicula. Nam justo justo, commodo nec volutpat quis, iaculis a dolor. Donec vitae justo egestas, pellentesque eros congue, venenatis justo. Mauris ornare tortor quis rutrum porta.",
];

let lastValue = 1;


function updatePar(value) {
    if (value !== undefined && value !== null)
        lastValue = value;
    else
        value = lastValue;

    $('textarea').val(loremData.slice(0, value).join("\n\n"))
    navigator.clipboard.writeText(loremData.slice(0, value).join("\n"))

    $('h2').addClass('flash')
    setTimeout(() => {
        $('h2').removeClass('flash')
    }, 100)

}

$(document).ready(() =>  {
    $(document).focus()
    updatePar(1)
});

